name: Node.js CI

on:
  push:
    branches:
      - modernization
  pull_request:
    branches:
      - modernization
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build:
    name: Build and Tests
    runs-on: ubuntu-latest  

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        id: test
        run: npm test

      - name: Upload Logs
        if: ${{ failure() }}  # Upload logs only if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.node-version }}  # Use node version in artifact name
          path: /home/runner/.npm/_logs/*.log

  finalize:
    needs: build  # Ensure this runs after the build job
    runs-on: ubuntu-latest
    steps:
      - name: Set CI status
        if: failure()  # Mark the workflow as failed if any job failed
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const octokit = new github.getOctokit(context.token);
            octokit.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'failure',
              context: 'CI',
              description: 'Tests failed'
            });
